### ISSUE TITLE
Can't find your wiki

### ISSUE THREAD

**Issue by browntownington** [wesleydmscn/opl-toolbox#14]
Hey there,

I was curious to learn more about your project. The wiki link (and other links) on your readme point to what looks to be a previous repo or this repo renamed. But also the wiki doesn't appear to be accessible.

Just a heads up incase you werent aware :)

**Comment by wesleydmscn** [comment]
Hi @browntownington . I am very happy that you are interested in the project, I apologize for the idea of ​​the project being unclear, this is due to the lack of time to dedicate to the project. However, I will give you a description of the idea for this project in case you want to help me with contributions.

In short, OPL Toolbox is a Linux desktop application built using GTK + Gnome Builder, previously the base was supposed to be in Python and for some reasons during the time it decided to switch to JavaScript to make it more open and accessible. The application consists of providing utility tools to automate OPL tasks, such as converting bin/cue games to VCD, installing Apps (.elf) and other common tasks of the Playstation 2 OPL ecosystem.

In Windows it is possible to do many things to use with OPL, most of the time the programs are one for each functionality. With OPL Toolbox I want to centralize all these functionalities in an easy way and with a nice interface for Linux users, since there are no tools like Windows for Linux

If you would like more details about my vision for this project as a whole, you can contact me on Discord or by email.

**Discord Username**: wesleydmscn
**Email**: wesleydmscno@gmail.com
